config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tickets do
    resources :troubleshooting_tasks
  end

  resources :user_troubleshooting_tasks, only: :update

  root to: 'tickets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  has_many :troubleshooting_tasks, dependent: :destroy
  has_many :ticket_troubleshooting_tasks

  validates :customer_name, :customer_address, :customer_phone_number, presence: true
  validates :customer_phone_number, numericality: { only_integer: true }
end

app/models/troubleshooting_task.rb
class TroubleshootingTask < ApplicationRecord
  belongs_to :ticket
  has_many :user_troubleshooting_tasks, dependent: :destroy
  has_many :users, through: :user_troubleshooting_tasks

  validates :description, presence: true
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :validatable, :omniauth_providers => [:facebook]
  has_many :tickets, dependent: :destroy
  has_many :user_troubleshooting_tasks, dependent: :destroy
  has_many :troubleshooting_tasks, through: :user_troubleshooting_tasks

  validates :name, presence: true

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name # assuming the user model has a name
    end
  end
end

app/models/user_troubleshooting_task.rb
class UserTroubleshootingTask < ApplicationRecord
  belongs_to :user
  belongs_to :troubleshooting_task

  STATUS = ['in progress', 'pending', 'canceled', 'completed'].freeze

  validates :status, inclusion: { in: STATUS }, presence: true, on: :update
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :find_ticket, only: [:edit, :update, :destroy, :show]

  def index
    @tickets = current_user.tickets.sort_by(&:customer_name)
    @troubleshooting_tasks = current_user.troubleshooting_tasks
  end

  def show
    @troubleshooting_tasks = @ticket.troubleshooting_tasks
  end 
  
  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user

    if @ticket.save
      redirect_to tickets_path, notice: "ticket succesfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to tickets_path, notice: "ticket succesfully updated"
    else
      render :edit
    end  
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path, notice: "ticket succesfully deleted"
  end

  private

  def ticket_params
    params.require(:ticket).permit(:customer_name, :customer_address, :customer_phone_number, :customer_details)
  end

  def find_ticket
    @ticket = Ticket.find_by(id: params[:id])
  end
end

app/controllers/troubleshooting_tasks_controller.rb
class TroubleshootingTasksController < ApplicationController
  before_action :find_ticket 
  before_action :find_task, only: [:edit, :update, :show, :destroy]

  def new
    @troubleshooting_task = @ticket.troubleshooting_tasks.new
  end

  def create
    @troubleshooting_task = @ticket.troubleshooting_tasks.new(troubleshooting_task_params)
      if @troubleshooting_task.save
        redirect_to ticket_path(@ticket), notice: "task succesfully created"
    else
      pp @troubleshooting_task.errors.full_messages
      pp params
      render :new
    end
  end

  def show
    
  end

  def edit
    @user_troubleshooting_task = current_user.user_troubleshooting_tasks.find_by(troubleshooting_task: @troubleshooting_task)
  end

  def update
    if @troubleshooting_task.update(troubleshooting_task_params)
      redirect_to ticket_path(@ticket), notice: "ticket succesfully updated"
    else
      render :edit
    end  
  end

  def destroy
    @troubleshooting_task.destroy
    redirect_to ticket_path(@ticket), notice: "ticket succesfully deleted"
  end


  private 

  def troubleshooting_task_params
    params.require(:troubleshooting_task).permit(:description, user_ids: [])
  end

  def find_ticket
    @ticket = Ticket.find_by(id: params[:ticket_id])
  end

  def find_task
    @troubleshooting_task = @ticket.troubleshooting_tasks.find_by(id: params[:id])
  end
end

app/controllers/user_troubleshooting_tasks_controller.rb
class UserTroubleshootingTasksController < ApplicationController
  def update
    @user_troubleshooting_task = UserTroubleshootingTask.find_by(id: params[:id])
    @ticket = @user_troubleshooting_task.troubleshooting_task.ticket
    if @user_troubleshooting_task.update(task_params)
      redirect_to root_path, notice: 'task updated'
    else
      render 'troubleshooting_tasks/edit'
    end
  end

  private

  def task_params
    params.require(:user_troubleshooting_task).permit(:notes, :status)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 
  <%= link_to 'Technician Note Book', root_path, class:"navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
          <%= link_to 'Logout', destroy_user_session_path, class:"nav-link", method: :delete %>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>TechnicianNotebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    
    <%= render "layouts/navbar"%>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/tickets/_form.html.erb
<%= simple_form_for @ticket do |f| %>
  <%= f.input :customer_name %>
  <%= f.input :customer_address %>
  <%= f.input :customer_phone_number %>
  <%= f.input :customer_details %>
  <%= f.button :submit, class:'btn btn-primary' %>
<% end %>

app/views/tickets/_ticket.html.erb
<tr>
  <td><%= ticket.customer_name %></td>
  <td><%= ticket.customer_address %></td>
  <td><%= ticket.customer_phone_number %></td>
  <td>
    <%= link_to 'View', ticket_path(ticket) %>
    <%= link_to 'Edit', edit_ticket_path(ticket) %>
    <%= link_to 'Delete', ticket_path(ticket), method: :delete,
    data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/tickets/edit.html.erb
<h1>Edit Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<div class="jumbotron center">
  <h1>Welcome <%= current_user.name %> </h1>
  <h2> Create tickets here </h2>
  <%= link_to "Add Ticket", new_ticket_path, class:'btn btn-success' %>
</div>

<h2>Tickets</h2>
<%if @tickets.empty? %>
  <p>No tickets</p>
<%else%>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Customer Name</th>
        <th>Customer Address</th>
        <th>Phone Number</th>
        <th></th>
      </tr>
    </thead>  
    <tbody>
      <%= render @tickets %>
    </tbody>
  </table>
<% end %>
 
 <h2>My assigned Tasks</h2>
<%if @troubleshooting_tasks.empty? %>
  <p>you dont have any Tasks at the moment</p>
<%else%>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th>Description</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>  
    <tbody>
      <%= render @troubleshooting_tasks %>
    </tbody>
  </table>
<% end %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p><%= @ticket.customer_name %></p>
<p><%= @ticket.customer_address %></p>
<p><%= @ticket.customer_phone_number %></p>
<p><%= @ticket.customer_details %></p>

<%= link_to 'Back', tickets_path %>
<%= link_to "Add Task", new_ticket_troubleshooting_task_path(ticket_id: @ticket.id), class:'btn btn-primary' %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Description</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>  
  <tbody>
    <%= render @troubleshooting_tasks %>
  </tbody>
</table>

app/views/troubleshooting_tasks/_form.html.erb
<%= simple_form_for [@ticket, @troubleshooting_task] do |f| %>
  <%= f.input :description %>
  <%= f.association :users, label_method: :name, value_method: :id, as: :check_boxes %>
  <%= f.button :submit, class:'btn btn-primary' %>
<% end %>

app/views/troubleshooting_tasks/_troubleshooting_task.html.erb
<% ticket = troubleshooting_task.ticket %>
<% user_troubleshooting_task = troubleshooting_task.user_troubleshooting_tasks.find_by(user: current_user) %>

<tr>
  <td><%= troubleshooting_task.description %></td>
  <td><%= user_troubleshooting_task&.status %> </td>
  <td>
    <%= link_to 'View', ticket_troubleshooting_task_path(ticket_id: ticket.id, id: troubleshooting_task.id) %>
    <%= link_to 'Edit', edit_ticket_troubleshooting_task_path(ticket_id: ticket.id, id: troubleshooting_task.id) %>
    <% if ticket.user == current_user %>
        <%= link_to 'Delete', ticket_troubleshooting_task_path(ticket_id: ticket.id, id: troubleshooting_task.id),
        method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </td>
</tr>

app/views/troubleshooting_tasks/edit.html.erb
<h1>Edit Task</h1>
<% if @ticket.user == current_user %>
  <%= render 'form' %>
<% end %>
<% if @user_troubleshooting_task %>
  <%= render 'user_troubleshooting_tasks/task_details' %>
<% else %>
  <p> You are not Authorized to Edit this page </p>
<% end %>

<%= link_to 'Back', ticket_path(@ticket) %>


app/views/troubleshooting_tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_path(@ticket) %>

app/views/troubleshooting_tasks/show.html.erb
<% user_tasks = @troubleshooting_task.user_troubleshooting_tasks %>

<p>This task has <%= pluralize(user_tasks.count, 'Technician') %> currently assigned </p>

<p><%= @troubleshooting_task.description %></p>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Technician </th>
      <th>Status</th>
    </tr>
  </thead>  
  <tbody>
    <% user_tasks.each do |user_task| %>
      <tr>
        <td><%= user_task.user.name %></td>
         <td><%= user_task.status %></td>
      </tr>
    <% end %> 
   
  </tbody>
</table>

<p><%= link_to 'Back', ticket_path(@ticket) %></p>


app/views/user_troubleshooting_tasks/_task_details.html.erb
<%= simple_form_for @user_troubleshooting_task, method: :put do |f| %>
  <%= f.input :notes %>
  <%= f.input :status, collection: UserTroubleshootingTask::STATUS %>
  <%= f.button :submit, class:'btn btn-primary' %>
<% end %>


app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>